language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
before_install:
  - pip install codecov

install:
  - pip install .
  - pip install pytest
# command to run tests
script:
  - py.test tests

after_success:
  - codecov
  - pep8 --ignore=E501 .
